### ISSUE TITLE
add usecase exampl

### ISSUE THREAD

**Issue by AndreyMlashkin** [Tereius/conan-linuxdeployqt#1]
Could you please add a small description how to use the tool?

**Comment by Tereius** [comment]
Hi,

the description of how to use the tool itself can be found here: https://github.com/probonopd/linuxdeployqt

This repository contains only the conan packaging instructions (recipe). You can use this package in your "conan aware" build process as follows:
* First add my conan artifactory: `conan remote add Tereius https://conan.privatehive.de/artifactory/api/conan/public-conan`
* Then reference this linuxdeployt package as a build dependency in your conanfile.py like so:
```
from conans import ConanFile, tools

class MyAppConan(ConanFile):
    name = "myapp"
    version = "1.0.0"
    requires = "Qt/5.15.2@tereius/stable"
    build_requires = "linuxdeployqt/6.0@tereius/stable" # reference 'linuxdeployt' as a build dependency
    #[...]
    def source(self):
       # download/source the source code of your app
    def build(self):
        # compile your app
    def package(self):
        # package your app by using linuxdeployqt. Make sure that the structure is correct: https://github.com/probonopd/linuxdeployqt#simplest-example
        self.run("%s/linuxdeployqt.AppImage ./AppDir/share/applications/myapp.desktop -appimage -no-translations -qmake=%s/bin/qmake -executable=./AppDir/bin/myapp" % (self.deps_cpp_info["linuxdeployqt"].rootpath, self.deps_cpp_info["Qt"].rootpath), cwd=self.package_folder)
```
* Build your app: `conan create . user/channel --build missing`

Make sure to use the oldest still-supported Ubuntu LTS to build your app. Otherwise linuxdeployqt won't work: https://github.com/probonopd/linuxdeployqt#a-note-on-binary-compatibility
